name: Claude Maintainer

on:
  schedule:
    # Semanalmente los domingos a las 9 AM UTC
    - cron: "0 9 * * 0"
  workflow_dispatch:
    # También se puede ejecutar manualmente

jobs:
  claude-maintainer:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Capture GDD baseline
        run: |
          node scripts/validate-gdd-runtime.js --full || true
          node scripts/score-gdd-health.js --ci || true
          node scripts/predict-gdd-drift.js --ci || true

      - name: Run ClaudeMaintainer
        id: maintainer
        run: |
          node scripts/claude-maintainer.js
        continue-on-error: true

      - name: Check for rollback
        if: steps.maintainer.outcome == 'failure'
        run: |
          echo "Rollback detected. Creating issue..."
          echo "REQUIRES_MANUAL_REVIEW=true" >> $GITHUB_ENV

      - name: Create Pull Request
        if: steps.maintainer.outcome == 'success'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Create branch
          git checkout -b maintenance/claude-updates-$(date +%Y%m%d)
          
          # Add changes
          git add docs/maintenance/ docs/telemetry/ || true
          
          # Commit
          git config user.name "ClaudeMaintainer Bot"
          git config user.email "claude-maintainer@roastr.ai"
          
          git commit -m "chore(claude): Auto-maintenance update $(date +%Y-%m-%d)" || echo "No changes to commit"
          
          # Push
          git push origin maintenance/claude-updates-$(date +%Y%m%d) || echo "Branch already exists"
          
          # Create PR
          gh pr create \
            --title "chore(claude): Auto-maintenance update $(date +%Y-%m-%d)" \
            --body "## Auto-maintenance Update
          
          This PR was automatically generated by ClaudeMaintainer.
          
          ### Reports
          - [Drift Report]($(gh api repos/:owner/:repo/contents/docs/maintenance/claude-drift-report.md --jq .download_url))
          - [Changelog]($(gh api repos/:owner/:repo/contents/docs/maintenance/claude-changelog.md --jq .download_url))
          
          ### Review Required
          Please review the changes before merging.
          " || echo "PR already exists"

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: claude-maintainer-reports
          path: |
            docs/maintenance/*.md
            docs/telemetry/*.json
          retention-days: 90

      - name: Comment on rollback
        if: env.REQUIRES_MANUAL_REVIEW == 'true'
        uses: actions/github-script@v8
        with:
          script: |
            const fs = require('fs');
            const rollbackReport = fs.readFileSync('docs/maintenance/claude-rollback-report.md', 'utf8');
            
            // Find or create issue
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '⚠️ ClaudeMaintainer Rollback - Manual Review Required',
              body: rollbackReport,
              labels: ['maintenance', 'claude', 'priority:P1']
            });

