name: GDD Telemetry Collection

on:
  # Run daily at 00:00 UTC
  schedule:
    - cron: '0 0 * * *'

  # Manual trigger
  workflow_dispatch:

  # Optional: Run on PR to main (for testing)
  pull_request:
    branches: [main, develop]
    paths:
      - 'docs/nodes/**'
      - 'scripts/collect-gdd-telemetry.js'
      - 'telemetry-config.json'

jobs:
  collect-telemetry:
    runs-on: ubuntu-latest
    name: Collect GDD Telemetry Metrics

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for momentum calculation

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run GDD validation (generate fresh data)
        run: |
          node scripts/validate-gdd-runtime.js --ci || true
          node scripts/score-gdd-health.js --ci || true
          node scripts/predict-gdd-drift.js --ci || true

      - name: Collect telemetry
        id: telemetry
        continue-on-error: ${{ github.event_name == 'pull_request' }}
        run: |
          # C1: Run collector (allow failure with || true so status extraction always runs)
          node scripts/collect-gdd-telemetry.js --ci || true

          # M1: Extract status with error handling (fix jq extraction errors)
          if [ -f telemetry/snapshots/gdd-metrics-history.json ]; then
            STATUS=$(jq -r '.snapshots[-1].metrics.derived.system_status // "UNKNOWN"' telemetry/snapshots/gdd-metrics-history.json 2>/dev/null || echo "UNKNOWN")
            echo "status=${STATUS}" >> $GITHUB_OUTPUT
          else
            echo "::error::Telemetry collector failed to generate snapshot"
            echo "status=ERROR" >> $GITHUB_OUTPUT
          fi

          # P1-1: Propagate failures when collector fails or status is UNKNOWN
          # Only fail in scheduled/manual runs (not PRs - handled by continue-on-error)
          if [ "${{ github.event_name }}" != "pull_request" ]; then
            if [ ! -f telemetry/snapshots/gdd-metrics-history.json ] || [ "${STATUS}" = "UNKNOWN" ] || [ "${STATUS}" = "ERROR" ]; then
              echo "::error::Collector failed to generate valid snapshot or status (STATUS=${STATUS})"
              exit 1
            fi
          fi

      - name: Commit telemetry data
        if: github.event_name != 'pull_request'  # M1 Fix: Skip on PR events
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore(telemetry): Daily GDD metrics snapshot [skip ci]"
          file_pattern: |
            telemetry/snapshots/gdd-metrics-history.json
            telemetry/reports/*.md
            gdd-status.json
            gdd-health.json
            gdd-drift.json
            docs/drift-report.md
            docs/system-health.md
            docs/system-validation.md
          commit_user_name: "gdd-telemetry-bot"
          commit_user_email: "bot@gdd-telemetry.local"
          commit_author: "GDD Telemetry Bot <bot@gdd-telemetry.local>"
          skip_dirty_check: false
          skip_fetch: false
          skip_checkout: false

      - name: Upload telemetry artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gdd-telemetry-${{ github.run_number }}
          path: |
            telemetry/snapshots/gdd-metrics-history.json
            telemetry/reports/*.md
          retention-days: 30

      - name: Check for critical alerts
        if: steps.telemetry.outputs.status == 'CRITICAL'
        run: |
          echo "::warning::GDD system status is CRITICAL"
          exit 1

      - name: Create issue on critical failure
        if: failure() && steps.telemetry.outputs.status == 'CRITICAL'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const reportPath = 'telemetry/reports/gdd-telemetry-' + new Date().toISOString().split('T')[0] + '.md';

            // M2: Add file safety checks before reading
            let issueBody;
            if (!fs.existsSync(reportPath)) {
              console.error('Report file not found:', reportPath);
              // Create issue with basic info instead
              issueBody = `## 🚨 GDD System Status Alert\n\n` +
                          `The GDD telemetry system has detected a **CRITICAL** status.\n\n` +
                          `**Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n\n` +
                          `**Note:** Detailed report unavailable (file not generated).`;
            } else {
              const report = fs.readFileSync(reportPath, 'utf8');
              issueBody = `## 🚨 GDD System Status Alert\n\n` +
                          `The GDD telemetry system has detected a **CRITICAL** status.\n\n` +
                          `**Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}\n\n` +
                          `---\n\n` +
                          report;
            }

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '[GDD Telemetry] System Status: CRITICAL',
              body: issueBody,
              labels: ['gdd', 'tech-debt', 'priority:P1', 'documentation']
            });

permissions:
  contents: write
  issues: write
  pull-requests: write
