name: Claude with Custom App

on:
  issue_comment:
    types: [created]
  # Puedes añadir otros triggers si quieres que responda también a PRs, pushes, etc.
  # pull_request:
  #   types: [opened, synchronize, reopened]

jobs:
  claude-response:
    runs-on: ubuntu-latest
    steps:
      # 1. Generar token desde tu GitHub App
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      # 2. Ejecutar acción de Claude usando tu API Key y token generado
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ steps.app-token.outputs.token }}
          mode: app
